/* genres.c -- dev-time tool: bake resource directories into headers/res_data.h.
 *
 * usage: genres <out_header> <name=dir> [<name=dir> ...]
 *
 * For each <name=dir> it emits one `static const unsigned char[]` per file plus
 * a `<name>_table[]` of {name,data,size} keyed by exact basename, and a
 * <NAME>_COUNT macro.  E.g.  genres headers/res_data.h res=../res city=../cities
 * produces res_table[]/RES_COUNT and city_table[]/CITY_COUNT.
 *
 * Run via `make resdata` when res/ or cities/ change; the generated header is
 * committed so the plain-cc game build never needs this tool.  Runs on the
 * build host only, so it needs no old-Unix portability.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

#define MAXF 512

static int
scmp(const void *a, const void *b)
{
  return strcmp(*(char *const *)a, *(char *const *)b);
}

/* file basename -> C identifier fragment (non-alnum becomes '_') */
static void
mangle(const char *in, char *out)
{
  int i;
  for (i = 0; in[i]; i++) {
    char c = in[i];
    int ok = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') ||
	     (c >= 'A' && c <= 'Z');
    out[i] = ok ? c : '_';
  }
  out[i] = 0;
}

/* emit all files in <dir> as `<name>_*` arrays plus `<name>_table[]`. */
static int
emit_table(FILE *out, const char *name, const char *dir)
{
  char *files[MAXF];
  int n = 0, i;
  char up[64];
  DIR *d;
  struct dirent *e;

  if ((d = opendir(dir)) == NULL) { perror(dir); return -1; }
  while ((e = readdir(d)) != NULL && n < MAXF) {
    char p[1024];
    struct stat st;
    if (e->d_name[0] == '.') continue;
    sprintf(p, "%s/%s", dir, e->d_name);
    if (stat(p, &st) != 0 || !S_ISREG(st.st_mode)) continue;
    files[n++] = strdup(e->d_name);
  }
  closedir(d);
  qsort(files, n, sizeof(char *), scmp);

  for (i = 0; i < n; i++) {
    char p[1024], id[128];
    FILE *f;
    int c, col = 0;
    sprintf(p, "%s/%s", dir, files[i]);
    mangle(files[i], id);
    if ((f = fopen(p, "rb")) == NULL) { perror(p); return -1; }
    fprintf(out, "static const unsigned char %s_%s[] = {\n", name, id);
    while ((c = getc(f)) != EOF) {
      fprintf(out, "0x%02x,", (unsigned)c);
      if (++col == 16) { fputc('\n', out); col = 0; }
    }
    if (col) fputc('\n', out);
    fprintf(out, "};\n\n");
    fclose(f);
  }

  fprintf(out, "static const struct EmbeddedRes %s_table[] = {\n", name);
  for (i = 0; i < n; i++) {
    char id[128];
    mangle(files[i], id);
    fprintf(out, "  { \"%s\", %s_%s, (unsigned int)sizeof(%s_%s) },\n",
	    files[i], name, id, name, id);
  }
  fprintf(out, "};\n");

  for (i = 0; name[i]; i++) up[i] = (name[i] >= 'a' && name[i] <= 'z')
			       ? name[i] - 'a' + 'A' : name[i];
  up[i] = 0;
  fprintf(out, "#define %s_COUNT ((int)(sizeof(%s_table) / sizeof(%s_table[0])))\n\n",
	  up, name, name);

  fprintf(stderr, "genres:   %s_table[%d] from %s\n", name, n, dir);
  return n;
}

int
main(int argc, char **argv)
{
  FILE *out;
  int a;

  if (argc < 3) {
    fprintf(stderr, "usage: %s <out.h> <name=dir> [<name=dir> ...]\n", argv[0]);
    return 2;
  }
  if ((out = fopen(argv[1], "w")) == NULL) { perror(argv[1]); return 1; }

  fprintf(out,
    "/* res_data.h -- GENERATED by genres.c.  Do not edit by hand.\n"
    " * Embeds the game's resource directories (string tables, scenarios and\n"
    " * the bundled example cities) into the binary so nothing is loaded from\n"
    " * disk at runtime.  Regenerate with `make resdata`. */\n\n"
    "struct EmbeddedRes {\n"
    "  const char *name;\n"
    "  const unsigned char *data;\n"
    "  unsigned int size;\n"
    "};\n\n");

  for (a = 2; a < argc; a++) {
    char *spec = argv[a], *eq = strchr(spec, '=');
    if (!eq) { fprintf(stderr, "bad spec '%s' (want name=dir)\n", spec); return 2; }
    *eq = 0;
    if (emit_table(out, spec, eq + 1) < 0) { fclose(out); return 1; }
  }

  fclose(out);
  fprintf(stderr, "genres: wrote %s\n", argv[1]);
  return 0;
}
